version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "template-lambda-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-6ge24nirg7k8"
s3_prefix = "template-lambda-app"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=084882962555.dkr.ecr.us-west-2.amazonaws.com/template-lambda"]
