- run: docker build --tag ${{ github.repository.name }} .
- name: Deploy to ECR
  id: ecr
  uses: jwalton/gh-ecr-push@v1
  with:
    access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    region: us-west-2
    local-image: lambda-template
    image: ${{ github.repository.name }}:${{ github.sha }}
